name: Report_robot_logs

# read-write repo token
# access to secrets
# tmp
on:
  workflow_run:
    workflows: ['Deploy_to_test']
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "sha"
            })[0];
            var download = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/sha.zip', Buffer.from(download.data));
      - run: unzip sha.zip
      - name: 'Get sha Number'
        id: fetch_sha
        uses: actions/github-script@v6
        with:
          script: |
            var fs = require('fs');
            var issue_number = String(fs.readFileSync('./NR'));
            return issue_number

      - name: 'Send report to commit'
        uses: joonvena/robotframework-reporter-action@v2.1
        with:
          report_path: reports
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          show_passed_tests: true
          sha: ${{steps.fetch_sha.outputs.result}}
      - run: echo "${{steps.fetch_sha.outputs.result}}"
